[package]
name = "rfloat"
version = "0.1.0"
authors = ["GHIAT Houssem <ghiat.houssem@gmail.com>"]
build = "build.rs"

[dependencies]
num-traits = "*"
[dev-dependencies]
frounding = "*"
[build-dependencies]
gcc = "0.3.0"
cupid = "*"
